import os

HTML = []

def add(s):
    HTML.append(s)

def write():
    path = 'docs/leads/steuerberater-wehling-terfort/index.html'
    with open(path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(HTML))
    print(f'Written {len(HTML)} parts to {path}')

# Build HTML
add('<!DOCTYPE html>')
add('<html lang="de">')
add('<head>')
add('<meta charset="UTF-8">')
add('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
add('<meta name="description" content="Wehling & Terfort Steuerberatersozietat Bielefeld - Ihre Steuerkanzlei fur den Mittelstand seit 1965">')
add('<title>Wehling & Terfort | Steuerberater Bielefeld</title>')
add('<link rel="preconnect" href="https://fonts.googleapis.com">')
add('<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>')
add('<link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@300;400;500;600;700&display=swap" rel="stylesheet">')
add('<style>')
add(':root{--black:#0a0a0a;--white:#f5f5f5;--coral:#FF6B6B;--gray:#111;--gray-light:#1a1a1a;--gray-mid:#666;--gray-dim:#333;--font:"Space Grotesk",sans-serif;--max:1200px;--gap:clamp(1rem,4vw,3rem);--radius:4px}')
add('*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}')
add('html{scroll-behavior:smooth;font-size:16px}')
add('body{font-family:var(--font);background:var(--black);color:var(--white);line-height:1.5;-webkit-font-smoothing:antialiased;overflow-x:hidden}')
add('h1,h2,h3{font-weight:700;line-height:1.05}')
add('a{color:inherit;text-decoration:none}')
add('img{max-width:100%;display:block}')
add('.container{width:min(var(--max),100% - 2rem);margin-inline:auto}')
add('.section{padding:clamp(4rem,10vw,8rem) 0}')
add('.sr-only{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}')
add('.accent{color:var(--coral)}')
add('.btn{display:inline-flex;align-items:center;gap:.6em;padding:1em 2.2em;font-family:var(--font);font-weight:600;font-size:.95rem;letter-spacing:.02em;border:2px solid var(--coral);border-radius:var(--radius);cursor:pointer;transition:all .25s ease;text-transform:uppercase}')
add('.btn-primary{background:var(--coral);color:var(--black)}')
add('.btn-primary:hover,.btn-primary:focus-visible{background:transparent;color:var(--coral)}')
add('.btn-ghost{background:transparent;color:var(--white);border-color:var(--gray-dim)}')
add('.btn-ghost:hover,.btn-ghost:focus-visible{border-color:var(--coral);color:var(--coral)}')
add('.badge{display:inline-block;font-size:.75rem;font-weight:600;letter-spacing:.08em;text-transform:uppercase;color:var(--coral);margin-bottom:1rem}')
add('.num{font-size:clamp(4rem,10vw,8rem);font-weight:700;line-height:.9;color:var(--coral);display:block}')
add('.num-sm{font-size:clamp(2.5rem,6vw,4rem);font-weight:700;line-height:1;color:var(--coral);display:block;margin-bottom:.3em}')
add('.grid{display:grid;gap:var(--gap)}')
add('.grid-2{grid-template-columns:repeat(auto-fit,minmax(min(100%,320px),1fr))}')
add('.grid-3{grid-template-columns:repeat(auto-fit,minmax(min(100%,280px),1fr))}')
add('header{position:fixed;top:0;left:0;right:0;z-index:100;padding:1.2rem 0;transition:background .3s ease}')
add('header.scrolled{background:rgba(10,10,10,.92);backdrop-filter:blur(12px);-webkit-backdrop-filter:blur(12px)}')
add('header .container{display:flex;justify-content:space-between;align-items:center}')
add('.logo{font-size:1.15rem;font-weight:700;letter-spacing:-.02em;line-height:1.2}')
add('.logo span{display:block;font-size:.7rem;font-weight:400;letter-spacing:.05em;text-transform:uppercase;color:var(--gray-mid)}')
add('.nav-links{display:flex;gap:1.8rem;list-style:none}')
add('.nav-links a{font-size:.8rem;font-weight:500;letter-spacing:.04em;text-transform:uppercase;transition:color .2s;padding:.3em 0;border-bottom:2px solid transparent}')
add('.nav-links a:hover,.nav-links a:focus-visible{color:var(--coral);border-bottom-color:var(--coral)}')
add('.hamburger{display:none;flex-direction:column;gap:5px;cursor:pointer;background:none;border:none;padding:4px;z-index:101}')
add('.hamburger span{display:block;width:24px;height:2px;background:var(--white);transition:all .3s}')
add('.hamburger.active span:nth-child(1){transform:rotate(45deg) translate(5px,5px)}')
add('.hamburger.active span:nth-child(2){opacity:0}')
add('.hamburger.active span:nth-child(3){transform:rotate(-45deg) translate(5px,-5px)}')
add('.hero{min-height:100vh;display:flex;align-items:center;background:var(--black);position:relative}')
add('.hero::before{content:"";position:absolute;top:0;right:0;width:50%;height:100%;background:radial-gradient(ellipse at center,rgba(255,107,107,.08) 0%,transparent 70%)}')
add('.hero-content{position:relative;z-index:1}')
add('.hero .num{font-size:clamp(5rem,15vw,12rem);margin-bottom:.05em;animation:fadeUp .8s ease}')
add('.hero h1{font-size:clamp(2rem,5vw,3.5rem);max-width:14ch;margin-bottom:.8em;animation:fadeUp .8s .15s ease both}')
add('.hero .btn{margin-top:.5em;animation:fadeUp .8s .3s ease both}')
add('@keyframes fadeUp{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}')
add('.section-label{font-size:.75rem;font-weight:600;letter-spacing:.1em;text-transform:uppercase;color:var(--gray-mid);margin-bottom:2rem;display:flex;align-items:center;gap:1em}')
add('.section-label::after{content:"";flex:1;height:1px;background:var(--gray-dim)}')
add('h2{font-size:clamp(2rem,4vw,3rem);margin-bottom:1em;max-width:16ch}')
add('.services .grid{gap:clamp(2rem,5vw,4rem)}')
add('.service-card{counter-increment:service;position:relative;padding:2.5rem 0;border-top:1px solid var(--gray-dim)}')
add('.service-card::before{content:"0" counter(service);font-size:3rem;font-weight:700;color:var(--coral);display:block;margin-bottom:1.5rem;line-height:1}')
add('.service-card h3{font-size:1.5rem;margin-bottom:.6em}')
add('.service-card p{color:var(--gray-mid);max-width:40ch;font-size:.95rem;line-height:1.7}')
add('.service-card .service-list{list-style:none;margin-top:1.2rem;display:flex;flex-wrap:wrap;gap:.5rem}')
add('.service-card .service-list li{font-size:.8rem;color:var(--gray-mid);padding:.35em .9em;border:1px solid var(--gray-dim);border-radius:var(--radius)}')
add('.why{background:var(--gray)}')
add('.stat-card{text-align:left;padding:2rem 0}')
add('.stat-card p{color:var(--gray-mid);font-size:.9rem;margin-top:.5em;max-width:24ch}')
add('.team-card{position:relative;padding:2rem 0;border-top:1px solid var(--gray-dim)}')
add('.team-avatar{width:80px;height:80px;border-radius:50%;background:var(--gray-light);margin-bottom:1.5rem;position:relative;overflow:hidden}')
add('.team-avatar::after{content:"";position:absolute;bottom:0;left:50%;transform:translateX(-50%);width:60%;height:55%;background:var(--gray-dim);border-radius:50% 50% 0 0}')
add('.team-avatar::before{content:"";position:absolute;top:20%;left:50%;transform:translateX(-50%);width:38%;height:38%;background:var(--gray-dim);border-radius:50%}')
add('.team-card h3{font-size:1.2rem;margin-bottom:.2em}')
add('.team-card .role{font-size:.75rem;text-transform:uppercase;letter-spacing:.06em;color:var(--coral);margin-bottom:.8em}')
add('.team-card p{color:var(--gray-mid);font-size:.85rem;max-width:32ch;line-height:1.7}')
add('.contact{position:relative}')
add('.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:clamp(2rem,6vw,5rem);align-items:start}')
add('.contact-info h2{margin-bottom:.5em}')
add('.contact-details{margin-top:2rem;display:flex;flex-direction:column;gap:1.2rem}')
add('.contact-details dt{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:var(--gray-mid);margin-bottom:.3em}')
add('.contact-details dd{font-size:1rem}')
add('.contact-details a:hover{color:var(--coral)}')
add('.hours{margin-top:2rem}')
add('.hours h4{font-size:.8rem;text-transform:uppercase;letter-spacing:.06em;margin-bottom:1em;color:var(--gray-mid)}')
add('.hours-table{width:100%;max-width:320px;border-collapse:collapse}')
add('.hours-table td{padding:.35em 0;font-size:.85rem;border-bottom:1px solid var(--gray-dim)}')
add('.hours-table td:last-child{text-align:right;color:var(--gray-mid)}')
add('.form{display:flex;flex-direction:column;gap:1.2rem}')
add('.form-group{display:flex;flex-direction:column;gap:.4em}')
add('.form-group label{font-size:.7rem;text-transform:uppercase;letter-spacing:.08em;color:var(--gray-mid)}')
add('.form-group input,.form-group textarea,.form-group select{padding:.9em 1.2em;background:var(--gray-light);border:1px solid var(--gray-dim);border-radius:var(--radius);color:var(--white);font-family:var(--font);font-size:.9rem;transition:border-color .25s;outline:none}')
add('.form-group input:focus,.form-group textarea:focus{border-color:var(--coral)}')
add('.form-group textarea{min-height:120px;resize:vertical}')
add('.form-row{display:grid;grid-template-columns:1fr 1fr;gap:1rem}')
add('.form-check{display:flex;align-items:flex-start;gap:.7em;font-size:.75rem;color:var(--gray-mid);line-height:1.5}')
add('.form-check input{width:16px;height:16px;margin-top:2px;accent-color:var(--coral);flex-shrink:0}')
add('.form-check a{color:var(--coral);text-decoration:underline}')
add('footer{padding:2.5rem 0;border-top:1px solid var(--gray-dim);margin-top:clamp(3rem,8vw,6rem)}')
add('footer .container{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:1rem}')
add('footer p{font-size:.75rem;color:var(--gray-mid)}')
add('footer nav{display:flex;gap:1.5rem}')
add('footer nav a{font-size:.75rem;color:var(--gray-mid);transition:color .2s}')
add('footer nav a:hover{color:var(--coral)}')
add('.toast{position:fixed;bottom:2rem;right:2rem;background:var(--coral);color:var(--black);padding:1em 1.8em;border-radius:var(--radius);font-weight:600;font-size:.9rem;transform:translateY(100px);opacity:0;transition:all .35s ease;z-index:200;pointer-events:none}')
add('.toast.show{transform:translateY(0);opacity:1}')
add('@media(max-width:768px){')
add('.hamburger{display:flex}')
add('.nav-links{position:fixed;top:0;right:-100%;width:70%;max-width:320px;height:100vh;background:var(--gray);flex-direction:column;justify-content:center;align-items:flex-start;padding:4rem 2rem;transition:right .35s ease;gap:2rem}')
add('.nav-links.active{right:0}')
add('.nav-links a{font-size:1.2rem}')
add('.contact-grid{grid-template-columns:1fr}')
add('.form-row{grid-template-columns:1fr}')
add('footer .container{flex-direction:column;text-align:center}')
add('}')
add('@media(max-width:480px){')
add('.logo{font-size:1rem}')
add('.hero .num{font-size:clamp(3.5rem,12vw,5rem)}')
add('}')
add('</style>')
add('</head>')
